const DB_KEY='xb_entregas_v3';const SESSION_KEY='xb_entregas_session';
const titles={dashboard:'Dashboard',newDelivery:'Nova entrega',deliveries:'Entregas',couriers:'Entregadores',closing:'Fechamento',reports:'Relatórios',settings:'Configurações'};
const $=id=>document.getElementById(id);const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const uid=(p='id')=>`${p}_${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`;
function dateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function fmtDateTime(v){if(!v)return'-';return new Date(v).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function initialDB(){return{settings:{storeName:'X-Burguer Entregas',defaultFee:6,email:'admin@xburguer.com',password:'123456'},couriers:[{id:'carlos',name:'Carlos Oliveira',phone:'(62) 99999-1111',fee:6,active:true},{id:'ana',name:'Ana Paula',phone:'(62) 99999-2222',fee:6,active:true},{id:'bruno',name:'Bruno Santos',phone:'(62) 99999-3333',fee:6,active:true}],deliveries:[],closings:[]}}
function loadDB(){try{const raw=localStorage.getItem(DB_KEY);if(!raw)return initialDB();const data=JSON.parse(raw),base=initialDB();return{settings:{...base.settings,...(data.settings||{})},couriers:Array.isArray(data.couriers)?data.couriers:[],deliveries:Array.isArray(data.deliveries)?data.deliveries:[],closings:Array.isArray(data.closings)?data.closings:[]}}catch{return initialDB()}}
let db=loadDB();function save(){localStorage.setItem(DB_KEY,JSON.stringify(db))}save();
function toast(msg,type='ok'){const e=document.createElement('div');e.className=`toast ${type}`;e.textContent=msg;$('toasts').appendChild(e);setTimeout(()=>e.remove(),3200)}
function courier(id){return db.couriers.find(c=>c.id===id)}function todayDeliveries(){const t=dateKey();return db.deliveries.filter(d=>dateKey(new Date(d.createdAt))===t)}function delivered(list){return list.filter(d=>d.status==='Entregue')}
function nextCode(){return db.deliveries.length?Math.max(...db.deliveries.map(d=>Number(d.code||0)))+1:1}
function statusClass(s){return{'Aguardando':'waiting','Em rota':'route','Entregue':'done','Cancelada':'cancel'}[s]||'waiting'}
function statusHTML(s){return `<span class="status ${statusClass(s)}">${esc(s)}</span>`}
function stat(icon,klass,value,label,detail=''){return `<div class="stat"><div class="stat-top"><div class="stat-icon ${klass}">${icon}</div><span class="stat-detail">${detail}</span></div><div class="stat-value">${value}</div><div class="stat-label">${label}</div></div>`}
function empty(title,text){return `<div class="empty"><b>${title}</b><span>${text}</span></div>`}
function initials(name){return String(name||'').split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function openModal(id){$(id).classList.add('open')}function closeModal(id){$(id).classList.remove('open')}

document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));

$('loginForm').addEventListener('submit',e=>{e.preventDefault();if($('loginEmail').value.trim()===db.settings.email&&$('loginPassword').value===db.settings.password){sessionStorage.setItem(SESSION_KEY,'1');showApp()}else toast('E-mail ou senha incorretos.','error')});
$('logoutBtn').addEventListener('click',()=>{sessionStorage.removeItem(SESSION_KEY);location.reload()});
function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');renderAll()}
if(sessionStorage.getItem(SESSION_KEY)==='1')showApp();

function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));$(`page-${page}`).classList.add('active');document.querySelector(`.nav-btn[data-page="${page}"]`)?.classList.add('active');$('topTitle').textContent=titles[page]||'X-Burguer';closeSidebar();renderAll()}
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
$('mobileMenu').addEventListener('click',()=>{$('sidebar').classList.toggle('open');$('drawerBackdrop').classList.toggle('open')});$('drawerBackdrop').addEventListener('click',closeSidebar);
function closeSidebar(){$('sidebar').classList.remove('open');$('drawerBackdrop').classList.remove('open')}

function renderSelects(){const active=db.couriers.filter(c=>c.active);$('deliveryCourier').innerHTML='<option value="">Selecione um entregador</option>'+active.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('editDeliveryCourier').innerHTML='<option value="">Sem entregador</option>'+db.couriers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}
$('deliveryCourier').addEventListener('change',e=>{const c=courier(e.target.value);if(c)$('deliveryFee').value=Number(c.fee||0).toFixed(2)});

$('deliveryForm').addEventListener('submit',e=>{e.preventDefault();const item={id:uid('delivery'),code:nextCode(),client:$('deliveryClient').value.trim()||'Cliente',phone:$('deliveryPhone').value.trim(),address:$('deliveryAddress').value.trim(),reference:$('deliveryReference').value.trim(),courierId:$('deliveryCourier').value||null,fee:Number($('deliveryFee').value||0),orderValue:Number($('deliveryValue').value||0),payment:document.querySelector('input[name="payment"]:checked').value,notes:$('deliveryNotes').value.trim(),status:'Aguardando',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};db.deliveries.push(item);save();e.target.reset();$('deliveryFee').value=Number(db.settings.defaultFee).toFixed(2);$('deliveryValue').value='0';toast(`Entrega #${String(item.code).padStart(3,'0')} cadastrada.`);go('deliveries')});

function renderDashboard(){const t=todayDeliveries(),done=delivered(t),wait=t.filter(x=>x.status==='Aguardando'),route=t.filter(x=>x.status==='Em rota'),revenue=done.reduce((s,x)=>s+Number(x.orderValue||0),0);$('dashboardStats').innerHTML=stat('▣','red',t.length,'Entregas hoje','Total')+stat('⌁','blue',route.length,'Em rota agora','Ativas')+stat('✓','green',done.length,'Entregues','Hoje')+stat('R$','orange',money(revenue),'Pedidos entregues','Hoje');const items=[...db.deliveries].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,5);$('recentDeliveries').innerHTML=items.length?`<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Entregador</th><th>Status</th></tr></thead><tbody>${items.map(i=>`<tr><td><span class="table-name">${esc(i.client)}</span><span class="table-muted">#${String(i.code).padStart(3,'0')}</span></td><td>${esc(courier(i.courierId)?.name||'Não definido')}</td><td>${statusHTML(i.status)}</td></tr>`).join('')}</tbody></table></div>`:empty('Nenhuma entrega','Cadastre sua primeira entrega.');$('operationSummary').innerHTML=`<div class="summary-list"><div class="summary-row"><span>Aguardando entregador</span><b>${wait.length}</b></div><div class="summary-row"><span>Em rota</span><b>${route.length}</b></div><div class="summary-row"><span>Entregadores ativos</span><b>${db.couriers.filter(c=>c.active).length}</b></div><div class="summary-row total"><span>Taxas realizadas</span><b>${money(done.reduce((s,x)=>s+Number(x.fee||0),0))}</b></div></div>`}

function filterRange(items,range){if(range==='all')return items;if(range==='today'){const t=dateKey();return items.filter(i=>dateKey(new Date(i.createdAt))===t)}const limit=new Date();limit.setDate(limit.getDate()-Number(range));return items.filter(i=>new Date(i.createdAt)>=limit)}
$('deliverySearch').addEventListener('input',renderDeliveries);$('statusFilter').addEventListener('change',renderDeliveries);$('dateFilter').addEventListener('change',renderDeliveries);
function renderDeliveries(){const q=$('deliverySearch').value.trim().toLowerCase(),status=$('statusFilter').value,range=$('dateFilter').value;let items=filterRange([...db.deliveries],range);if(status)items=items.filter(i=>i.status===status);if(q)items=items.filter(i=>[i.client,i.address,i.phone,courier(i.courierId)?.name].join(' ').toLowerCase().includes(q));items.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));$('deliveryStats').innerHTML=stat('▣','red',db.deliveries.length,'Total de entregas')+stat('◷','orange',db.deliveries.filter(i=>i.status==='Aguardando').length,'Aguardando')+stat('⌁','blue',db.deliveries.filter(i=>i.status==='Em rota').length,'Em rota')+stat('✓','green',db.deliveries.filter(i=>i.status==='Entregue').length,'Entregues');$('deliveriesTable').innerHTML=items.length?`<table><thead><tr><th>#</th><th>Cliente</th><th>Endereço</th><th>Entregador</th><th>Pedido</th><th>Taxa</th><th>Status</th><th>Ações</th></tr></thead><tbody>${items.map(i=>`<tr><td>#${String(i.code).padStart(3,'0')}</td><td><span class="table-name">${esc(i.client)}</span><span class="table-muted">${fmtDateTime(i.createdAt)}</span></td><td>${esc(i.address)}${i.reference?`<span class="table-muted">${esc(i.reference)}</span>`:''}</td><td>${esc(courier(i.courierId)?.name||'Não definido')}</td><td>${money(i.orderValue)}</td><td>${money(i.fee)}</td><td>${statusHTML(i.status)}</td><td><div class="row-actions">${!['Entregue','Cancelada'].includes(i.status)?`<button class="icon-btn" title="Avançar status" onclick="advanceDelivery('${i.id}')">→</button>`:''}<button class="icon-btn" title="Editar" onclick="editDelivery('${i.id}')">✎</button>${!['Entregue','Cancelada'].includes(i.status)?`<button class="icon-btn" title="Cancelar" onclick="cancelDelivery('${i.id}')">⊘</button>`:''}<button class="icon-btn" title="Excluir" onclick="deleteDelivery('${i.id}')">⌫</button></div></td></tr>`).join('')}</tbody></table>`:empty('Nenhuma entrega encontrada','Altere os filtros ou cadastre uma nova entrega.')}
window.advanceDelivery=id=>{const i=db.deliveries.find(x=>x.id===id);if(!i)return;if(i.status==='Aguardando')i.status='Em rota';else if(i.status==='Em rota')i.status='Entregue';i.updatedAt=new Date().toISOString();save();toast(`Status alterado para ${i.status}.`);renderAll()};
window.cancelDelivery=id=>{const i=db.deliveries.find(x=>x.id===id);if(!i||!confirm('Deseja cancelar esta entrega?'))return;i.status='Cancelada';i.updatedAt=new Date().toISOString();save();toast('Entrega cancelada.');renderAll()};
window.deleteDelivery=id=>{if(!confirm('Excluir definitivamente esta entrega?'))return;db.deliveries=db.deliveries.filter(x=>x.id!==id);save();toast('Entrega excluída.');renderAll()};
window.editDelivery=id=>{const i=db.deliveries.find(x=>x.id===id);if(!i)return;$('editDeliveryId').value=i.id;$('editDeliveryClient').value=i.client||'';$('editDeliveryPhone').value=i.phone||'';$('editDeliveryAddress').value=i.address||'';$('editDeliveryCourier').value=i.courierId||'';$('editDeliveryValue').value=i.orderValue||0;$('editDeliveryFee').value=i.fee||0;openModal('deliveryModal')};
$('deliveryEditForm').addEventListener('submit',e=>{e.preventDefault();const i=db.deliveries.find(x=>x.id===$('editDeliveryId').value);if(!i)return;i.client=$('editDeliveryClient').value.trim()||'Cliente';i.phone=$('editDeliveryPhone').value.trim();i.address=$('editDeliveryAddress').value.trim();i.courierId=$('editDeliveryCourier').value||null;i.orderValue=Number($('editDeliveryValue').value||0);i.fee=Number($('editDeliveryFee').value||0);i.updatedAt=new Date().toISOString();save();closeModal('deliveryModal');toast('Entrega atualizada.');renderAll()});

$('newCourierBtn').addEventListener('click',()=>openCourier());
function openCourier(id=''){$('courierForm').reset();$('courierId').value=id;$('courierFee').value=Number(db.settings.defaultFee).toFixed(2);$('courierActive').value='true';$('courierModalTitle').textContent=id?'Editar entregador':'Novo entregador';if(id){const c=courier(id);if(!c)return;$('courierName').value=c.name;$('courierPhone').value=c.phone||'';$('courierFee').value=c.fee;$('courierActive').value=String(c.active)}openModal('courierModal')}window.openCourier=openCourier;
$('courierForm').addEventListener('submit',e=>{e.preventDefault();const id=$('courierId').value,data={name:$('courierName').value.trim(),phone:$('courierPhone').value.trim(),fee:Number($('courierFee').value||0),active:$('courierActive').value==='true'};if(id){Object.assign(courier(id),data);toast('Entregador atualizado.')}else{db.couriers.push({id:uid('courier'),...data});toast('Entregador cadastrado.')}save();closeModal('courierModal');renderAll()});
window.deleteCourier=id=>{if(db.deliveries.some(i=>i.courierId===id)){toast('Esse entregador possui entregas. Marque como inativo em vez de excluir.','error');return}if(!confirm('Excluir este entregador?'))return;db.couriers=db.couriers.filter(c=>c.id!==id);save();toast('Entregador excluído.');renderAll()};
function renderCouriers(){const active=db.couriers.filter(c=>c.active),done=db.deliveries.filter(i=>i.status==='Entregue'),avg=active.length?active.reduce((s,c)=>s+Number(c.fee||0),0)/active.length:0;$('courierStats').innerHTML=stat('♟','red',db.couriers.length,'Equipe cadastrada')+stat('✓','green',active.length,'Entregadores ativos')+stat('R$','orange',money(avg),'Taxa média')+stat('▣','blue',done.length,'Entregas concluídas');$('courierGrid').innerHTML=db.couriers.length?db.couriers.map(c=>{const items=done.filter(i=>i.courierId===c.id),fees=items.reduce((s,i)=>s+Number(i.fee||0),0);return `<div class="courier-card"><div class="courier-top"><div class="courier-person"><div class="courier-avatar">${initials(c.name)}</div><div><strong>${esc(c.name)}</strong><span>${esc(c.phone||'Sem telefone')}</span></div></div><div class="dot ${c.active?'':'off'}"></div></div><div class="courier-data"><div><span>Taxa padrão</span><strong>${money(c.fee)}</strong></div><div><span>Entregas</span><strong>${items.length}</strong></div></div><div class="courier-data"><div><span>Taxas recebidas</span><strong>${money(fees)}</strong></div><div><span>Status</span><strong>${c.active?'Ativo':'Inativo'}</strong></div></div><div class="courier-actions"><button class="btn btn-light btn-sm" onclick="openCourier('${c.id}')">Editar</button><button class="btn btn-danger btn-sm" onclick="deleteCourier('${c.id}')">Excluir</button></div></div>`}).join(''):empty('Nenhum entregador','Cadastre sua equipe de entregas.')}

function renderClosing(){const t=todayDeliveries(),done=delivered(t),pending=t.filter(i=>['Aguardando','Em rota'].includes(i.status)),orders=done.reduce((s,i)=>s+Number(i.orderValue||0),0),fees=done.reduce((s,i)=>s+Number(i.fee||0),0);$('closingStats').innerHTML=stat('R$','green',money(orders),'Pedidos entregues')+stat('¤','red',money(fees),'Total em taxas')+stat('✓','blue',done.length,'Entregas realizadas')+stat('◷','orange',pending.length,'Pendentes');const pays={Dinheiro:0,PIX:0,'Cartão':0};done.forEach(i=>{if(pays[i.payment]!==undefined)pays[i.payment]+=Number(i.orderValue||0)});$('closingPayments').innerHTML=Object.entries(pays).map(([name,val])=>{const pct=orders?Math.round(val/orders*100):0;return `<div class="pay-row"><div class="pay-top"><span>${name}</span><b>${money(val)} · ${pct}%</b></div><div class="progress"><span style="width:${pct}%"></span></div></div>`}).join('')+`<div class="summary-row total"><span>Total</span><b>${money(orders)}</b></div>`;const rows=db.couriers.map(c=>{const items=done.filter(i=>i.courierId===c.id);return{c,count:items.length,value:items.reduce((s,i)=>s+Number(i.fee||0),0)}}).filter(r=>r.count);$('closingCouriers').innerHTML=rows.length?`<div class="summary-list">${rows.map(r=>`<div class="summary-row"><span>${esc(r.c.name)} · ${r.count} entrega${r.count===1?'':'s'}</span><b>${money(r.value)}</b></div>`).join('')}</div>`:empty('Sem entregas concluídas','Os valores aparecerão aqui.');const close=db.closings.find(c=>c.date===dateKey());if(close){$('closingBanner').innerHTML=`<div class="banner ok">✓ Dia finalizado em ${fmtDateTime(close.closedAt)}.</div>`;$('closeDayBtn').classList.add('hidden');$('reopenDayBtn').classList.remove('hidden')}else{$('closingBanner').innerHTML=pending.length?`<div class="banner warn">⚠ Existem <b>${pending.length}</b> entregas pendentes. Confira antes de finalizar o dia.</div>`:'';$('closeDayBtn').classList.remove('hidden');$('reopenDayBtn').classList.add('hidden')}}
$('closeDayBtn').addEventListener('click',()=>{const d=dateKey();if(db.closings.some(c=>c.date===d))return;const t=todayDeliveries(),done=delivered(t),pending=t.filter(i=>['Aguardando','Em rota'].includes(i.status));if(pending.length&&!confirm(`Existem ${pending.length} entregas pendentes. Finalizar mesmo assim?`))return;db.closings.push({id:uid('closing'),date:d,delivered:done.length,pending:pending.length,orderValue:done.reduce((s,i)=>s+Number(i.orderValue||0),0),fees:done.reduce((s,i)=>s+Number(i.fee||0),0),closedAt:new Date().toISOString()});save();toast('Fechamento do dia finalizado.');renderClosing()});
$('reopenDayBtn').addEventListener('click',()=>{if(!confirm('Deseja reabrir o fechamento de hoje?'))return;db.closings=db.closings.filter(c=>c.date!==dateKey());save();toast('Fechamento reaberto.');renderClosing()});

$('reportRange').addEventListener('change',renderReports);function reportItems(){let items=db.deliveries.filter(i=>i.status==='Entregue'),range=$('reportRange').value;if(range==='all')return items;const limit=new Date();limit.setDate(limit.getDate()-Number(range));return items.filter(i=>new Date(i.createdAt)>=limit)}
function renderReports(){const items=reportItems(),revenue=items.reduce((s,i)=>s+Number(i.orderValue||0),0),fees=items.reduce((s,i)=>s+Number(i.fee||0),0),avg=items.length?revenue/items.length:0;$('reportStats').innerHTML=stat('R$','green',money(revenue),'Faturamento')+stat('¤','red',money(fees),'Taxas de entrega')+stat('✓','blue',items.length,'Entregas')+stat('≋','purple',money(avg),'Ticket médio');const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=dateKey(d);days.push({label:d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}),count:items.filter(x=>dateKey(new Date(x.createdAt))===key).length})}const max=Math.max(1,...days.map(d=>d.count));$('reportChart').innerHTML=days.map(d=>`<div class="chart-item"><div class="chart-value">${d.count}</div><div class="chart-bar" style="height:${Math.max(4,d.count/max*100)}%"></div><div class="chart-label">${d.label}</div></div>`).join('');const pays={Dinheiro:0,PIX:0,'Cartão':0};items.forEach(i=>{if(pays[i.payment]!==undefined)pays[i.payment]++});const total=items.length||1;$('paymentReport').innerHTML=Object.entries(pays).map(([n,c])=>{const p=Math.round(c/total*100);return `<div class="pay-row"><div class="pay-top"><span>${n}</span><b>${c} · ${p}%</b></div><div class="progress"><span style="width:${p}%"></span></div></div>`}).join('');const rank=db.couriers.map(c=>({name:c.name,count:items.filter(i=>i.courierId===c.id).length})).sort((a,b)=>b.count-a.count),rmax=Math.max(1,...rank.map(r=>r.count));$('courierRanking').innerHTML=rank.some(r=>r.count)?rank.map(r=>`<div class="pay-row"><div class="pay-top"><span>${esc(r.name)}</span><b>${r.count}</b></div><div class="progress"><span style="width:${r.count/rmax*100}%"></span></div></div>`).join(''):empty('Sem dados suficientes','As entregas concluídas aparecerão aqui.')}

function renderSettings(){$('storeName').value=db.settings.storeName;$('defaultFee').value=db.settings.defaultFee;$('settingEmail').value=db.settings.email;$('settingPassword').value=db.settings.password}
$('settingsForm').addEventListener('submit',e=>{e.preventDefault();db.settings.storeName=$('storeName').value.trim()||'X-Burguer Entregas';db.settings.defaultFee=Number($('defaultFee').value||0);save();toast('Configurações atualizadas.');renderAll()});
$('credentialsForm').addEventListener('submit',e=>{e.preventDefault();const email=$('settingEmail').value.trim(),pass=$('settingPassword').value;if(!email||!pass)return toast('Informe e-mail e senha.','error');db.settings.email=email;db.settings.password=pass;save();toast('Dados de acesso atualizados.')});
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
$('backupBtn').addEventListener('click',()=>{download(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),`xburguer-backup-${dateKey()}.json`);toast('Backup gerado.')});$('restoreBtn').addEventListener('click',()=>$('backupFile').click());$('backupFile').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const imported=JSON.parse(r.result);if(!Array.isArray(imported.deliveries)||!Array.isArray(imported.couriers))throw 0;if(!confirm('Restaurar este backup? Os dados atuais serão substituídos.'))return;db=imported;save();toast('Backup restaurado.');setTimeout(()=>location.reload(),600)}catch{toast('Arquivo de backup inválido.','error')}};r.readAsText(f)});
$('clearDataBtn').addEventListener('click',()=>{if(!confirm('Tem certeza? Todas as entregas e fechamentos serão apagados.'))return;db.deliveries=[];db.closings=[];save();toast('Entregas e fechamentos apagados.');renderAll()});
$('exportCsvBtn').addEventListener('click',()=>{const h=['Código','Data','Cliente','Telefone','Endereço','Entregador','Pedido','Taxa','Pagamento','Status'];const rows=db.deliveries.map(i=>[i.code,new Date(i.createdAt).toLocaleString('pt-BR'),i.client,i.phone||'',i.address,courier(i.courierId)?.name||'',Number(i.orderValue||0).toFixed(2),Number(i.fee||0).toFixed(2),i.payment,i.status]);const csv=[h,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');download(new Blob(['\uFEFF',csv],{type:'text/csv;charset=utf-8'}),`xburguer-entregas-${dateKey()}.csv`);toast('CSV exportado.')});

function renderAll(){$('todayLabel').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short',year:'numeric'});renderSelects();renderDashboard();renderDeliveries();renderCouriers();renderClosing();renderReports();renderSettings();if(!$('deliveryFee').value)$('deliveryFee').value=Number(db.settings.defaultFee).toFixed(2)}
